---
title: "Evidencia 2 | Proyecto integrador"
author: "Ernesto Andre González Castro, A01741225"
date: "`r Sys.Date()`"
output: html_document
---

```{r Codigos de Genbak}
variantes <- c("OQ928765", "OQ701260","OQ921107", "OQ059025", "OQ888915", "OX466324", "OM945722", "ON115271", "OQ748861", "OQ676999", "OP303172", "OQ748862", "OP412818", "OQ457497", "OU327282", "MZ570430", "OQ826413", "OQ120890", "ON545852", "OP013083")
```

```{r Librerias}
library(Biostrings)
library(seqinr)
library(adegenet)
library(ape)
library(ggtree)
library(DECIPHER)
library(viridis)
library(ggplot2)
```

```{r Leer codigos}
variantes_secuencias <- read.GenBank(variantes)
```

```{r String}
str(variantes_secuencias)
```

```{r Juntar Strings}
names(variantes_secuencias) <- c("USA","INDIA","BRAZIL","RUSIA","FRANCIA","REINO UNIDO","TURQUÍA","ESPAÑA", "ITALIA", "ARGENTINA", "COLOMBIA", "ALEMANIA", "IRÁN", "MÉXICO", "POLONIA", "INDONESIA", "SUDÁFRICA", "PERÚ", "PAÍSES BAJOS", "CHILE") 
attributes(variantes_secuencias)
names(variantes_secuencias)
attr(variantes_secuencias, "Variantes")
```

```{r Recopilar Secuencias}
write.dna(variantes_secuencias,  file ="variantes_sec.fasta", format = "fasta", append =
FALSE, nbcol = 6, colsep = " ", colw = 10)
```

```{r Secuencias NoAlineadas}
variantes_sec_no_alineadas <- readDNAStringSet("variantes_sec.fasta", format = "fasta")
```

```{r Secuencias Alineadas}
variantes_sec_no_alineadas <- OrientNucleotides(variantes_sec_no_alineadas)

variantes_sec_alineadas <- AlignSeqs(variantes_sec_no_alineadas)
```

```{r Visualizar}
BrowseSeqs(variantes_sec_alineadas, highlight=0)
```

```{r Guardar Resultado }
writeXStringSet(variantes_sec_alineadas, file = "variantes_sec_alineadas.fasta")
```

```{r Leer Archivo}
variantes_alineadas <- read.alignment("variantes_sec_alineadas.fasta", format = "fasta") 
```

```{r Matriz}
matriz_distancia <- dist.alignment(variantes_alineadas, matrix = "similarity")
```

```{r Visualizar Matriz}

temp <- as.data.frame(as.matrix(matriz_distancia))
temp
table.paint(temp, cleg=0, clabel.row=.5, clabel.col=.5) + scale_color_viridis()

```

```{r Creacion Arbol}
variantes_filogenetico <- nj(matriz_distancia)
```

```{r Dibujar Arbol}
variantes_plot_filogenetico <- ladderize(variantes_filogenetico)
plot(variantes_plot_filogenetico,no.margin=TRUE,edge.width=0.5)
title("SARS_COV2, 20 países con más casos")
```

```{r Lista vacia}
lista_composicion <- list()
```

```{r Recorrer lista}
for (x in 1:20) {
  variante <- variantes_alineadas[[3]]
  variante <- variante[[x]]
  variante <- gsub("-","",variante)
  variante <- s2c(variante)
  tamano = length(variante)
  composicion = count(variante, word=1)
  lista_composicion[[x]] <- as.matrix(composicion)
  gc = GC(variante)
  cat((names(variantes_secuencias))[x], "- Ranking:",x,"\n")
  cat("Tamaño:",tamano, "\n")
  print(composicion)
  cat("Porcentaje GC:", "")
  cat(gc, "\n\n")
  barplot(composicion, main=(names(variantes_secuencias))[x], col = c("darkgreen", "darkblue", "red", "orange"))
  contrasentido = rev(variante)
  cat("Secuencia contrasentido\n")
  cat("Primeros 10 nucleótidos:", head(contrasentido, 30), "\n")
  cat("Últimos 10 nucleótidos:", tail(contrasentido, 30))
  cat("\n--------------------------------------------------\n")
}
```

```{r Gráfica}
matriz_composicion <- do.call(cbind, lista_composicion)

bp <- barplot(matriz_composicion, col = c("darkgreen", "darkblue", "red", "orange"),
        main="Composición de bases de ADN para todas las variantes del virus",
        xlab="Bases de ADN", ylab="Número de bases")

text(bp, 1:ncol(matriz_composicion), labels=1:ncol(matriz_composicion), pos=3)

legend("center", c("A", "C", "G", "T"), fill=c("darkgreen", "darkblue", "red", "orange"), title="Bases de ADN",bg="transparent", border=NA)


```